### ISSUE TITLE
Clearfix mixin missing

### ISSUE THREAD

**Issue by vladshap** [itsmattsoria/starthere#12]
When I run `yarn start` it complains about a missing clearfix mixin. Maybe I am missing something, in which case ignore me. 

Adding this to `_mixins.scss` fixed the nag for me though.

```// Clearfix
@mixin clearfix {
  &::after {
    content: "";
    display: table;
    clear: both;
  }
}
```

**Comment by itsmattsoria** [comment]
Fixed with https://github.com/itsmattsoria/starthere/commit/50e76821c6c00390a62a1b5272ab57e8da947543 🤓
